BaSP-TG: Created /super-admins endpoints. createSuperAdmin and getSuperAdminByID
BaSP-a2022/ayom-a-trackgenix-server pull request #14
Opened 2022-10-11 21:04 UTC by Eju97

Endpoints:

- /:id -> Returns the super-admin selected through ID.
- /createSuper-admin -> Creates a new super-admin and added into the array.

Added the route to the index.js file.

2022-10-13 02:04 UTC, paurinaldi requested changes

2022-10-13 02:04 UTC, paurinaldi commented on src/index.js
> +app.use('/super-admin', superadmin);
I would change to super-admins

2022-10-13 02:04 UTC, paurinaldi commented on src/resources/super-admins.js
> +router.post('/createSuper-admin', (req, res) => {
this endpoint is redundant, since the full route already has super-admins on it. I would just make it /add or /create

2022-10-13 02:04 UTC, paurinaldi commented on src/resources/super-admins.js
> +    res.send(`SuperAdmin ${req.body.email} created`);
I would just leave this message as Super admin created, or if you want to give more info, maybe using the first and last name would be more addecuate.

2022-10-13 17:33 UTC, paurinaldi submitted a review, later dismissed

2022-10-14 17:59 UTC, ignacioaristo approved these changes

2022-10-14 17:59 UTC, merged