BaSP-TG: Task Endpoints (GetOne, Update, Delete)
BaSP-a2022/ayom-a-trackgenix-server pull request #18
Opened 2022-10-17 00:41 UTC by Martinzancocchia

**

> endpoints added to tasks:

**

- getOne
- Update
- Delete

2022-10-17 01:47 UTC, ignacioaristo requested changes

2022-10-17 01:47 UTC, ignacioaristo commented on src/controllers/task.js
> +// import task from '../validations/task';
Remove this comment.

2022-10-17 01:47 UTC, ignacioaristo commented on src/controllers/task.js
> +      error: false,
I think this error is not necessary.

2022-10-17 01:47 UTC, ignacioaristo commented on src/controllers/task.js
> +      message: 'an error ocurred',
We can handle the error in a better way, for example, `message: 'an error ocurred: ${err}',`

2022-10-17 01:47 UTC, ignacioaristo commented on src/controllers/task.js
> +      error: err,
With the previous commet, we don't need this.

2022-10-17 01:47 UTC, ignacioaristo commented on src/controllers/task.js
> +    if (!id.match(/^[0-9a-fA-F]{24}$/)) {
For what is this for?

2022-10-17 01:47 UTC, ignacioaristo commented on src/controllers/task.js
> +        data: undefined,
This is not necessary.

2022-10-17 01:47 UTC, ignacioaristo commented on src/controllers/task.js
> +        data: undefined,
Same here.

2022-10-17 01:47 UTC, ignacioaristo commented on src/controllers/task.js
> +// export const createTask = async (req, res) => {
If we don't need this, remove all the comments lines.

2022-10-17 01:47 UTC, ignacioaristo commented on src/controllers/task.js
> +      msg: 'There has been an error:',
Let's handle the error message like the previous comment.

2022-10-17 01:47 UTC, ignacioaristo commented on src/controllers/task.js
> +// export {
I prefer use the export. But if you don't delete these commets.

2022-10-17 01:47 UTC, ignacioaristo commented on src/controllers/task.js
> +      msg: 'There has been an error',
Same error handling and delete the following props.

2022-10-17 01:47 UTC, ignacioaristo commented on src/index.js
> +// const tasksRouter = require('./resources/tasks');
Why comment these lines? The server will work if you uncomment this.

2022-10-17 01:47 UTC, ignacioaristo commented on src/index.js
> +// app.use('/projects', projectsRouter);
The same here.

2022-10-17 01:47 UTC, ignacioaristo commented on src/routes/task.js
> +// import validations from '../validations/task';
Delete all the comment lines

2022-10-17 01:47 UTC, ignacioaristo commented on src/routes/task.js
> +  .get('/', getAll);
This don't belong to this ticket.

2022-10-17 02:54 UTC, Martinzancocchia commented on src/controllers/task.js
> +// import task from '../validations/task';
done

2022-10-17 03:21 UTC, Martinzancocchia commented on src/controllers/task.js
> +      error: err,
done

2022-10-17 03:21 UTC, Martinzancocchia commented on src/controllers/task.js
> +    if (!id.match(/^[0-9a-fA-F]{24}$/)) {
fixed

2022-10-17 03:21 UTC, Martinzancocchia commented on src/controllers/task.js
> +        data: undefined,
fixed

2022-10-17 03:21 UTC, Martinzancocchia commented on src/controllers/task.js
> +        data: undefined,
done

2022-10-17 03:21 UTC, Martinzancocchia commented on src/controllers/task.js
> +      error: false,
done

2022-10-17 03:21 UTC, Martinzancocchia commented on src/controllers/task.js
> +      message: 'an error ocurred',
done

2022-10-17 03:21 UTC, Martinzancocchia commented on src/controllers/task.js
> +      error: err,
done

2022-10-17 03:21 UTC, Martinzancocchia commented on src/controllers/task.js
> +      msg: 'There has been an error',
done

2022-10-17 03:22 UTC, Martinzancocchia commented on src/index.js
> +// const tasksRouter = require('./resources/tasks');
done

2022-10-17 03:22 UTC, Martinzancocchia commented on src/index.js
> +// app.use('/projects', projectsRouter);
done

2022-10-17 03:22 UTC, Martinzancocchia commented on src/routes/task.js
> +// import validations from '../validations/task';
fixed

2022-10-17 03:22 UTC, Martinzancocchia commented on src/routes/task.js
> +  .get('/', getAll);
fixed!

2022-10-17 03:35 UTC, Martinzancocchia commented on src/controllers/task.js
> +// export const createTask = async (req, res) => {
done

2022-10-17 03:35 UTC, Martinzancocchia commented on src/controllers/task.js
> +      msg: 'There has been an error:',
done

2022-10-17 03:35 UTC, Martinzancocchia commented on src/controllers/task.js
> +// export {
fixed

2022-10-17 12:40 UTC, ignacioaristo requested changes

2022-10-17 12:40 UTC, ignacioaristo commented on src/index.js
> +// const tasksRouter = require('./resources/tasks');
i agree, but we can't have comment code. So for now you have to leave it, the other devs have to remove it from their PRs.

2022-10-17 12:40 UTC, ignacioaristo commented on src/routes/task.js
> +// import { updateTaskValidation } fr|om '../validations/task';
Delete this comment line

2022-10-17 22:53 UTC, paurinaldi requested changes

2022-10-17 22:53 UTC, paurinaldi commented on src/validations/task.js
> +  description: Joi.string().valid(
Since this is the only field, it should be required in order to update.

2022-10-17 23:07 UTC, paurinaldi commented on src/models/Task.js
> +    lowercase: true,
Why should we add this line?
I suggest you talk to sabri and you both establish the same shema for tasks.

2022-10-18 01:14 UTC, Martinzancocchia commented on src/validations/task.js
> +  description: Joi.string().valid(
Sorry! I just got out of an exam, when I get home I'll change it!

2022-10-18 01:14 UTC, Martinzancocchia commented on src/validations/task.js
> +  description: Joi.string().valid(
Sorry! I just got out of an exam, when I get home I'll change it!

2022-10-18 18:56 UTC, Martinzancocchia commented on src/routes/task.js
> +// import { updateTaskValidation } fr|om '../validations/task';
done

2022-10-19 23:24 UTC, paurinaldi requested changes

2022-10-19 23:24 UTC, paurinaldi commented on src/routes/index.js
please make it /tasks to keep consistency

2022-10-19 23:24 UTC, paurinaldi commented on src/index.js
> +app.use('/', routes);
we established route should be '/api'

2022-10-19 23:24 UTC, paurinaldi commented on src/controllers/task.js
> +    return res.status(200).json({
when we delete something from the database, status code should be 204

2022-10-20 02:16 UTC, paurinaldi commented on src/routes/index.js
I still see task as the route, should be /tasks

2022-10-20 02:34 UTC, paurinaldi approved these changes

2022-10-20 14:45 UTC, merged