BaSP-TG: Timesheet Endpoints (GetOne, Update, Delete)
BaSP-a2022/ayom-a-trackgenix-server pull request #19
Opened 2022-10-17 04:39 UTC by Martinzancocchia

2022-10-18 00:01 UTC, paurinaldi requested changes
I left many comments regarding starting to use timesheets as a single word, as it's more correct. Please, make necessary changes to keep consistency, including file names.

2022-10-18 18:57 UTC, Martinzancocchia commented on src/controllers/timeSheet.js
> +export const updateTS = async (req, res) => {
done

2022-10-18 18:57 UTC, Martinzancocchia commented on src/controllers/timeSheet.js
> +export const getOneTS = async (req, res) => {
done

2022-10-18 18:57 UTC, Martinzancocchia commented on src/controllers/timeSheet.js
> +export const deleteTS = async (req, res) => {
done

2022-10-18 19:04 UTC, Martinzancocchia commented on src/validations/timeSheet.js
> +    id: Joi.string().required,
done

2022-10-18 19:04 UTC, Martinzancocchia commented on src/validations/timeSheet.js
> +const TSValidateUpdate = Joi.object({
done

2022-10-18 19:04 UTC, Martinzancocchia commented on src/routes/index.js
> +router.use('/timeSheets', timeSheetRouter);
done

2022-10-18 19:04 UTC, Martinzancocchia commented on src/models/TimeSheet.js
> +export default mongoose.model('TimeSheet', timeSheetSchema);
done

2022-10-18 19:04 UTC, Martinzancocchia commented on src/models/TimeSheet.js
> +const timeSheetSchema = new Schema({
done

2022-10-18 19:04 UTC, Martinzancocchia commented on src/index.js
> -// app.listen(port, () => {
done

2022-10-19 23:42 UTC, paurinaldi requested changes

2022-10-19 23:42 UTC, paurinaldi commented on src/controllers/timeSheet.js
> +    return res.status(200).json({
when we succeded in deleting something from the database, status code should be 204

2022-10-19 23:42 UTC, paurinaldi commented on src/models/TimeSheet.js
> +    lowercase: true,
why should it be lowercase?

2022-10-20 02:32 UTC, paurinaldi commented on src/validations/timeSheet.js
> +const TimesheetValidateUpdate = Joi.object({
please do as you did on tasks branch, create one function with Joi schema inside.

2022-10-20 02:49 UTC, paurinaldi approved these changes

2022-10-20 03:12 UTC, paurinaldi commented on src/controllers/timeSheet.js
> +import Models from '../models/TimeSheet';
should be imported as TimesheetModel

2022-10-20 03:17 UTC, paurinaldi commented on src/validations/timeSheet.js
> +  const validation = taskValidation.validate(req.body);
You are using task validation, when you should be validating timesheets. Also, name of the const should start with lowercase, since we are using camelCase. ( should be timesheetValidateUpdate)

2022-10-20 03:31 UTC, Martinzancocchia commented on src/validations/timeSheet.js
> +  const validation = taskValidation.validate(req.body);
done

2022-10-20 03:37 UTC, Martinzancocchia commented on src/controllers/timeSheet.js
> +import Models from '../models/TimeSheet';
Done

2022-10-20 15:08 UTC, paurinaldi approved these changes

2022-10-20 15:08 UTC, merged