BaSP-TG-11: Employee Endpoints (GetAll and Create)
BaSP-a2022/ayom-a-trackgenix-server pull request #21
Opened 2022-10-17 18:11 UTC by eyrent

Added endpoints:

2022-10-18 11:07 UTC, eyrent commented
Comment on [this commit](https://github.com/BaSP-a2022/ayom-a-trackgenix-server/pull/21/commits/9431903689695bc4fa485fbd3b1415da0db715bf):

2022-10-18 12:14 UTC, paurinaldi requested changes
Please check that all functions are arrow functions all along your code. Other than that and others comments left, great work. Nice reducer, looking forward to see you explain it to your teammates 
:wink:

2022-10-18 12:54 UTC, eyrent commented on src/validations/employee.js
> +async function employeeValidatorMiddleware(req, res, next) {
I didn't get this. Are you talking about the `scheme.validateAsync()` fucntion? What I don't understand is that middleware functinos have the signature `middleware(req, res, next)` but AFIK Joi validate doesn't have that signature, therefore it would not be able to take the request object nor the `next` callback.

2022-10-18 13:09 UTC, eyrent commented on src/controllers/employee.js
> +const employeeDBController = {
I mades changes to this. But I'm not sure if this is OK. I mean the change of property names.

2022-10-18 13:57 UTC, eyrent commented on src/controllers/employee.js
> +async function createEmployeeMongo(req, res) {
Done!

2022-10-18 14:53 UTC, eyrent commented on src/validations/employee.js
> +async function employeeValidatorMiddleware(req, res, next) {
Oh! I think now I get what you meant: only the schema should be in this file. The middleware function should be somewhere else (presumably in `controllers/employee.js`). Anyhow I'll wait for you confirmation.

2022-10-18 16:45 UTC, paurinaldi commented on src/validations/employee.js
> +async function employeeValidatorMiddleware(req, res, next) {
What I'm suggesting, basically, is that you combine what you did in two separate functions, in one.

2022-10-18 19:18 UTC, eyrent commented on src/validations/employee.js
> +async function employeeValidatorMiddleware(req, res, next) {
I see what you mean now. Nevertheless, wouldn't that 'compile' a new schema everytime the middleware is executed?

2022-10-18 20:19 UTC, eyrent commented on src/validations/employee.js
> +async function employeeValidatorMiddleware(req, res, next) {
BTW, I'm making these changes you suggest to keep consistency because my teammates have the same approach too. I'll send you my previous question in Slack so we can finish with this PR and move on to the others. Thanks!

2022-10-19 23:47 UTC, paurinaldi approved these changes

2022-10-20 01:42 UTC, paurinaldi approved these changes

2022-10-20 01:42 UTC, merged