BaSP-TG-07:super-admin/endpoints/getAll-create
BaSP-a2022/ayom-a-trackgenix-server pull request #22
Opened 2022-10-17 19:11 UTC by matiasraviola

[GET] getAll: using the function find(), we can see all the super admin list.
[POST] create: using 'New' we can create a new super admin, only if the fields are filled in the body.

2022-10-18 16:59 UTC, paurinaldi requested changes

2022-10-18 16:59 UTC, paurinaldi commented on src/controllers/superAdmin.js
> +    const superAdmins = await SuperAdmin.find();
we should add logic to be able to filter

2022-10-18 16:59 UTC, paurinaldi commented on src/controllers/superAdmin.js
> +      message: 'An error occured ',
You could manage errors by adding the error message. Others have made it like this: 
message: 'an error ocurred: ${error}',
It would be good to implement it that way to keep consistency, and to show what the error is.

2022-10-18 16:59 UTC, paurinaldi commented on src/controllers/superAdmin.js
> +      error,
this line is not necessary

2022-10-18 16:59 UTC, paurinaldi commented on src/controllers/superAdmin.js
> +      message: 'An error occured ',
previous comment applies also to this.

2022-10-18 18:02 UTC, matiasraviola commented on src/controllers/superAdmin.js
> +      message: 'An error occured ',
done

2022-10-18 18:02 UTC, matiasraviola commented on src/controllers/superAdmin.js
> +      error,
done

2022-10-18 18:02 UTC, matiasraviola commented on src/controllers/superAdmin.js
> +      message: 'An error occured ',
done

2022-10-19 19:51 UTC, ignacioaristo approved these changes

2022-10-19 23:49 UTC, paurinaldi submitted a review, later dismissed

2022-10-19 23:50 UTC, ignacioaristo approved these changes

2022-10-19 23:59 UTC, paurinaldi approved these changes

2022-10-19 23:59 UTC, merged