BaSP-TG-06: Admin Endpoints (GetAll and Create)
BaSP-a2022/ayom-a-trackgenix-server pull request #23
Opened 2022-10-17 19:27 UTC by PilarFernandezC

- Create: creates an admin with the data completed in the body
- GetAll: shows a list of all the admins in the data base

2022-10-18 16:54 UTC, ignacioaristo requested changes
The postman collection is missing, we have to add the file.

2022-10-18 16:54 UTC, ignacioaristo commented on src/controllers/admins.js
> +      message: 'An error ocurred',
we can handle better this message, we can do somethin like : `message: 'An error ocurred': ${error}`

2022-10-18 16:54 UTC, ignacioaristo commented on src/controllers/admins.js
> +      error,
i think this prop is unnecessary.

2022-10-18 16:54 UTC, ignacioaristo commented on src/controllers/admins.js
> +    return res.json({
status code is missing.

2022-10-18 16:54 UTC, ignacioaristo commented on src/controllers/admins.js
> +      message: 'An error occurred',
same here

2022-10-18 16:54 UTC, ignacioaristo commented on src/controllers/admins.js
> +      error,
and here

2022-10-18 19:09 UTC, PilarFernandezC commented on src/controllers/admins.js
> +      message: 'An error ocurred',
done

2022-10-18 19:12 UTC, PilarFernandezC commented on src/controllers/admins.js
> +    return res.json({
I added it with an if, I don't know if it's ok

2022-10-18 19:13 UTC, PilarFernandezC commented on src/controllers/admins.js
> +      message: 'An error occurred',
done

2022-10-18 19:13 UTC, PilarFernandezC commented on src/controllers/admins.js
> +      error,
done

2022-10-19 19:46 UTC, ignacioaristo approved these changes

2022-10-20 01:07 UTC, paurinaldi approved these changes

2022-10-20 01:07 UTC, merged