BaSP-TG-05:Admin Endpoints (GetOne, Update, Delete)
BaSP-a2022/ayom-a-trackgenix-server pull request #24
Opened 2022-10-17 20:59 UTC by LucianoFranchino

2022-10-18 17:08 UTC, paurinaldi requested changes

2022-10-18 17:09 UTC, ignacioaristo requested changes

2022-10-18 17:09 UTC, ignacioaristo commented on src/controllers/admins.js
> +        error: false,
i think this prop is not necessary

2022-10-18 17:09 UTC, ignacioaristo commented on src/controllers/admins.js
> +      error: false,
same here

2022-10-18 17:09 UTC, ignacioaristo commented on src/controllers/admins.js
> +    return res.json({
the status code is missing.

2022-10-18 17:09 UTC, ignacioaristo commented on src/controllers/admins.js
> +      message: 'An error ocurred',
we can handle the message in a better way, for example: `message: 'Admin does not exists': ${error},`

2022-10-18 17:09 UTC, ignacioaristo commented on src/controllers/admins.js
> +      error,
same here, i think is not necessary

2022-10-18 17:09 UTC, ignacioaristo commented on src/controllers/admins.js
> +      { ...req.body },
spread operation is necessary here? I think `req.body` is enough

2022-10-18 17:09 UTC, ignacioaristo commented on src/controllers/admins.js
> +      error: false,
same here.

2022-10-18 17:09 UTC, ignacioaristo commented on src/controllers/admins.js
> +    return res.json({
status code is missing.

2022-10-18 17:09 UTC, ignacioaristo commented on src/controllers/admins.js
> +      message: 'An error occurred',
same error handling.

2022-10-18 17:09 UTC, ignacioaristo commented on src/controllers/admins.js
> +      message: 'An error has occurred',
same here.

2022-10-18 17:09 UTC, ignacioaristo commented on src/controllers/admins.js
> +      error,
same with this prop

2022-10-18 17:09 UTC, ignacioaristo commented on src/validations/admins.js
> +      data: undefined,
i think is not necessary to show the data as undefined, remove it.

2022-10-18 20:17 UTC, LucianoFranchino commented on src/controllers/admins.js
> +        error: false,
All the if? or just the return function?

2022-10-18 20:34 UTC, LucianoFranchino commented on src/controllers/admins.js
> +      { ...req.body },
It seemed to me that it was more optimal that way, in the same way I can take it out

2022-10-18 20:37 UTC, ignacioaristo commented on src/controllers/admins.js
> +        error: false,
Line 10

2022-10-18 20:37 UTC, ignacioaristo commented on src/controllers/admins.js
> +      error: false,
Line 16.

2022-10-19 17:19 UTC, ignacioaristo commented on src/controllers/admins.js
> +      $: { error },
Same here.

2022-10-19 18:15 UTC, LucianoFranchino commented on src/controllers/admins.js
> +      message: 'Admin does not exists',
Resolved

2022-10-19 18:15 UTC, LucianoFranchino commented on src/controllers/admins.js
> +      $: { error },
Resolved

2022-10-19 18:15 UTC, LucianoFranchino commented on src/controllers/admins.js
> +        error: false,
Resolved

2022-10-19 18:15 UTC, LucianoFranchino commented on src/controllers/admins.js
> +      $: { error },
Resolved

2022-10-19 18:45 UTC, merged