BaSP-TG-08: Super admin getById, update and delete endpoints
BaSP-a2022/ayom-a-trackgenix-server pull request #26
Opened 2022-10-18 03:17 UTC by mgriolfo-g

Endpoints created for super admin:

- [ ] `[GET] getSAdminById` -> ID param required in path. If found in the database, returns an array with the registered superadmin. 

- [ ] `[PUT] updateSAdmin` -> ID param required in path. If found in the database, proportioning a complete JSON in the body request allows the update of data of said ID (if validations are matched).

- [ ] `[DELETE] deleteSAdmin` -> ID param required in path. If found in the database, data related to said ID is erased.

2022-10-18 17:21 UTC, paurinaldi requested changes

2022-10-18 17:21 UTC, paurinaldi commented on src/controllers/superAdmin.js
> +      message: 'Error!',
previous comments also apply here

2022-10-18 20:27 UTC, mgriolfo-g commented on src/controllers/superAdmin.js
> +    const superAdmins = await superAdmin.findById(id);
changed to superAdminData since superAdmin is used as the model name (preserved this way to not generate conflict with other colleagues' work)

2022-10-18 20:50 UTC, mgriolfo-g commented on src/controllers/superAdmin.js
> +      { ...req.body },
taking out the spread operator results in a parsing error: unexpected token by eslint. How should I proceed? Asking my colleagues for similar situations

2022-10-18 21:11 UTC, mgriolfo-g commented on src/controllers/superAdmin.js
> +      { ...req.body },
Solved! @Eju97 's branch prompted me with the solution!

2022-10-19 23:52 UTC, paurinaldi approved these changes

2022-10-19 23:52 UTC, paurinaldi commented on src/controllers/superAdmin.js
> +    return res.status(200).json({
when we delete something from the database, status code should be 204

2022-10-20 00:19 UTC, paurinaldi requested changes
please change status code on delete controller

2022-10-20 12:05 UTC, paurinaldi submitted a review, later dismissed

2022-10-21 16:22 UTC, ignacioaristo approved these changes

2022-10-21 16:22 UTC, merged