BaSP-TG-13: Employee Endpoints (getEmployeeById, editEmployee, deleteEmployee)
BaSP-a2022/ayom-a-trackgenix-server pull request #27
Opened 2022-10-18 03:26 UTC by Eju97

Endpoints:

- getEmployeeById -> Return the employee selected by ID.
- editEmployee -> Edit and update the employee selected.
- deleteEmployee -> Deletes a selected employee by ID.

2022-10-18 18:01 UTC, paurinaldi requested changes

2022-10-18 18:01 UTC, paurinaldi commented on src/validations/employee.js
> +const employeeValidatorMiddleware = async (req, res, next) => {
This should not be a separate function, you could ombine it with employeeSchema.
You could start like this:

const validateUpdateEmployee = (req, res, next) => {
  const employeeUpdateSchema = Joi.object({

2022-10-19 19:41 UTC, ignacioaristo submitted a review, later dismissed

2022-10-19 22:13 UTC, ignacioaristo approved these changes

2022-10-19 22:14 UTC, merged