TG-17: Project Endpoints (GetOne, Update, Delete)
BaSP-a2022/ayom-a-trackgenix-server pull request #29
Opened 2022-10-19 00:19 UTC by eyrent

Created endpoints:

2022-10-19 00:27 UTC, eyrent commented
There might be changes pushed after this PR creation because I needed to hand in the PR's link.

2022-10-19 20:01 UTC, ignacioaristo approved these changes

2022-10-19 20:01 UTC, ignacioaristo commented on src/index.js
> -app.use('/projects', projectsRouter);
Delete only the entitiy that you have been working on, in that case the other devs will not have issues.

2022-10-19 20:40 UTC, eyrent commented on .vscode/settings.json
> +  "editor.detectIndentation": true,
Done.

2022-10-19 20:51 UTC, eyrent commented on src/index.js
> -app.use('/projects', projectsRouter);
Restored old routings.

2022-10-20 00:21 UTC, paurinaldi requested changes

2022-10-20 00:21 UTC, paurinaldi commented on src/controllers/projects.js
> +  } else {
For now, I would just leave res.status(500) on catch and delete this last else from all functions. Next planning we will establish a better way of handling errors and being able to set different codes.

2022-10-20 02:43 UTC, eyrent commented on src/controllers/projects.js
> +  } else {
Removed the elses. I didn't remove the id verification at the beginning since you didn't mention that specifically. I hope I've not mistaken you.

2022-10-20 02:51 UTC, paurinaldi approved these changes

2022-10-20 02:51 UTC, merged