BaSP-TG: for projects
BaSP-a2022/ayom-a-trackgenix-server pull request #3
Opened 2022-10-10 05:35 UTC by sabrina-reckinger

the JSON data was created and the modify,  delete and filter by part of the name functions was created.

2022-10-10 13:46 UTC, ignacioaristo commented on src/resources/projects.js
> +    const changeProject = req.body
; is missing

2022-10-10 22:53 UTC, sabrina-reckinger commented on src/resources/projects.js
> +    const changeProject = req.body
fixed

2022-10-10 22:54 UTC, sabrina-reckinger commented on src/resources/projects.js
> +const fs = require('fs')
fixed

2022-10-10 22:54 UTC, sabrina-reckinger commented
fixed all ;

2022-10-12 13:22 UTC, ignacioaristo requested changes

2022-10-12 13:22 UTC, ignacioaristo commented on src/index.js
> +
Delete this empty line

2022-10-12 13:22 UTC, ignacioaristo commented on src/index.js
> +
Delete this empty line

2022-10-12 13:22 UTC, ignacioaristo commented on src/resources/projects.js
> +    const projectId = parseInt(req.params.id);
We need to add a second parameter in `parseInt` method with value 10.

2022-10-12 13:22 UTC, ignacioaristo commented on src/resources/projects.js
> +    const projectId = parseInt(req.params.id);
The same here.

2022-10-14 04:41 UTC, sabrina-reckinger commented on src/index.js
> +
done

2022-10-14 04:42 UTC, sabrina-reckinger commented on src/index.js
> +
done

2022-10-14 04:42 UTC, sabrina-reckinger commented on src/resources/projects.js
> +    const projectId = parseInt(req.params.id);
done

2022-10-14 04:42 UTC, sabrina-reckinger commented on src/resources/projects.js
> +    const projectId = parseInt(req.params.id);
done

2022-10-14 11:34 UTC, paurinaldi requested changes

2022-10-14 11:34 UTC, paurinaldi commented on src/index.js
> +app.use("/tasks", tasksRouter);
delete duplicated line

2022-10-14 11:34 UTC, paurinaldi commented on src/index.js
>  app.use(projectRouter);
delete this line, it's incomplete and duplicated

2022-10-14 11:34 UTC, paurinaldi commented on src/resources/projects.js
>  const fs = require('fs');
delete duplicated lines

2022-10-14 13:17 UTC, sabrina-reckinger commented on src/index.js
> +app.use("/tasks", tasksRouter);
done

2022-10-14 13:27 UTC, sabrina-reckinger commented on src/resources/projects.js
>  const fs = require('fs');
done

2022-10-14 13:37 UTC, sabrina-reckinger commented on src/index.js
>  app.use(projectRouter);
done

2022-10-14 16:59 UTC, ignacioaristo requested changes
We have a lot of problems in the package-lock.json.
Delete this file, run npm install and update your local master with the origin.
If you have conflicts, keep the incoming changes.

2022-10-14 19:14 UTC, ignacioaristo approved these changes

2022-10-14 19:14 UTC, merged