BaSP-TG: Some endpoints added to time-sheets
BaSP-a2022/ayom-a-trackgenix-server pull request #4
Opened 2022-10-10 13:58 UTC by Martinzancocchia

1. **Endpoints added:**
- `getByDate`
- `getByDesc`
- `add`
- `deleteById`

2. Routing added to /time-sheets/XXXX

3. Data added to /time-sheets.json

2022-10-12 14:16 UTC, ignacioaristo requested changes

2022-10-12 14:16 UTC, ignacioaristo commented on src/resources/time-sheets.js
> +router.get('/getByDesc', (req, res) => {
Here the same, we miss the `/:description` to catch with the params.

2022-10-12 14:16 UTC, ignacioaristo commented on src/resources/time-sheets.js
> +  const queryDescription = req.query.description;
We are using params to retrieve the data, we need to change de `.query` for `.params`

2022-10-12 14:16 UTC, ignacioaristo commented on src/resources/time-sheets.js
> +    const targetTS = timeSheets.filter((current) => current.description === targetDesc).pop();
is this `.pop` neccesary?

2022-10-12 14:16 UTC, ignacioaristo commented on src/resources/time-sheets.js
> +router.delete('/deleteById', (req, res) => {
we need to add `/:id`

2022-10-12 14:16 UTC, ignacioaristo commented on src/resources/time-sheets.js
> +  const timeSheetsId = parseInt(req.query.id, 10);
change query for params

2022-10-12 14:16 UTC, ignacioaristo commented on src/resources/time-sheets.js
> +  const timeSheetsFilter = timeSheets.filter((timeSheet) => timeSheet.id !== timeSheetsId);
we need to parse to number the `timeSheetsId` in orden to make the delete method functional

2022-10-12 14:16 UTC, ignacioaristo commented on src/resources/time-sheets.js
> +  fileSystem.writeFile('src/data/time-sheets.json', JSON.stringify(timeSheetsFilter, null, '\n'), (err) => {
is no neccesary the second and third parameters in JSON.stringify

2022-10-12 14:16 UTC, ignacioaristo commented on src/resources/time-sheets.js
> +  const queryDate = req.query.date;
We need to replace query for params, we are working with params

2022-10-12 19:34 UTC, Martinzancocchia commented on src/resources/time-sheets.js
> +  const timeSheetsFilter = timeSheets.filter((timeSheet) => timeSheet.id !== timeSheetsId);
Hola Ayom, ya esta parseado, a que te referis?

2022-10-12 19:58 UTC, Martinzancocchia commented on src/resources/time-sheets.js
> +  const queryDate = req.query.date;
Buenas ayom, podemos dejar la fecha con query paramas, por el tema de las barras "/"

2022-10-13 17:11 UTC, ignacioaristo commented on src/resources/time-sheets.js
> +  const queryDate = req.query.date;
Ok, no problem in this case.

2022-10-13 17:15 UTC, ignacioaristo commented on src/resources/time-sheets.js
> +  const timeSheetsFilter = timeSheets.filter((timeSheet) => timeSheet.id !== timeSheetsId);
Right now the delete function is not working, if we remove the parseInt will work.

2022-10-13 17:42 UTC, ignacioaristo commented on src/resources/time-sheets.js
> +  fileSystem.writeFile('src/data/time-sheets.json', JSON.stringify(timeSheetsFilter, null, '\n'), (err) => {
Lets keep it anyway

2022-10-13 17:44 UTC, Martinzancocchia commented on src/index.js
> +app.use('/time-sheets', timeSheetsRouter);
done

2022-10-13 17:44 UTC, Martinzancocchia commented on src/resources/time-sheets.js
> +router.get('/getByDate', (req, res) => {
fixed

2022-10-13 17:44 UTC, Martinzancocchia commented on src/resources/time-sheets.js
> +router.get('/getByDesc', (req, res) => {
fixed!!!

2022-10-13 17:44 UTC, Martinzancocchia commented on src/resources/time-sheets.js
> +  const queryDescription = req.query.description;
done!

2022-10-13 17:44 UTC, Martinzancocchia commented on src/resources/time-sheets.js
> +    const targetTS = timeSheets.filter((current) => current.description === targetDesc).pop();
.pop deleted

2022-10-13 17:44 UTC, Martinzancocchia commented on src/resources/time-sheets.js
> +router.delete('/deleteById', (req, res) => {
added

2022-10-13 17:45 UTC, Martinzancocchia commented on src/resources/time-sheets.js
> +  const timeSheetsId = parseInt(req.query.id, 10);
done

2022-10-13 17:48 UTC, Martinzancocchia commented on src/resources/time-sheets.js
> +  fileSystem.writeFile('src/data/time-sheets.json', JSON.stringify(timeSheetsFilter, null, '\n'), (err) => {
that can stay, fabri has talked about it with you

2022-10-13 18:11 UTC, merged