BaSP-TG-29: Projects Unit Test get all, get id
BaSP-a2022/ayom-a-trackgenix-server pull request #41
Opened 2022-10-24 23:54 UTC by LucianoFranchino

2022-10-25 20:13 UTC, paurinaldi requested changes

2022-10-25 20:13 UTC, paurinaldi commented on src/seeds/projects.js
> +    _id: mongoose.Types.ObjectId('634d7e5757bc44f21a345462'),
shouldn't we be testing employeeId?

2022-10-25 20:15 UTC, paurinaldi commented on src/tests/projects.test.js
> +});
This should be closed at the bottom of all other describes. After line 42

2022-10-25 20:40 UTC, LucianoFranchino commented on src/tests/projects.test.js
> +});
Resolved

2022-10-25 20:40 UTC, LucianoFranchino commented on src/app.js
> +app.use('/', routes);
Resolved

2022-10-25 20:43 UTC, LucianoFranchino commented on src/seeds/projects.js
> +    _id: mongoose.Types.ObjectId('634d7e5757bc44f21a345462'),
I had understood that within the project you had to check the id, role and rate of the employee

2022-10-25 20:59 UTC, LucianoFranchino commented on src/seeds/projects.js
> +    _id: mongoose.Types.ObjectId('634d7e5757bc44f21a345462'),
Resolved

2022-10-27 02:11 UTC, paurinaldi approved these changes

2022-10-27 02:11 UTC, merged