BaSP-TG-35: Timesheet Unit Test - getAll, getById & delete
BaSP-a2022/ayom-a-trackgenix-server pull request #42
Opened 2022-10-25 14:54 UTC by matiasraviola

[delete] : tested when the id, route are wrong or when you forgot pass the id and when the id is valid
[getAll]: tested when you try to get all the list, filter by each field and when the route is wrong
[getById]: tested when you try to get a valid and/or invalid ID.

2022-10-25 17:27 UTC, PilarFernandezC commented on src/tests/timesheets.test.js
> +    expect(response.status).toBe(204);
you could also try testing the messages like this: `expect(response.body.message).toBe......`

2022-10-25 17:42 UTC, PilarFernandezC requested changes

2022-10-25 17:42 UTC, PilarFernandezC commented on src/tests/timesheets.test.js
> +    expect(response.status).toBe(204);
try testing the messages like this: `expect(response.body.message).toBe....... ` See in which tests you could do it.

2022-10-25 22:27 UTC, matiasraviola commented on src/tests/timesheets.test.js
> +    expect(response.status).toBe(204);
done

2022-10-26 21:25 UTC, PilarFernandezC approved these changes

2022-10-27 01:18 UTC, paurinaldi submitted a review, later dismissed
dismissed

2022-10-27 02:11 UTC, merged