BaSP-TG-37: Projects Unit Test - create, edit and delete
BaSP-a2022/ayom-a-trackgenix-server pull request #43
Opened 2022-10-25 15:29 UTC by PilarFernandezC

- create: tests when you send a correct body, a wrong body, a wrong route or you don´t send anything 
- delete: tests when you send a correct ID, a wrong ID, a wrong route or you don´t send anything
- edit:  tests when you send a correct ID, a wrong ID, a correct body, a wrong body, a wrong route or you don´t send anything

2022-10-25 17:37 UTC, matiasraviola requested changes

2022-10-25 17:37 UTC, matiasraviola commented on src/tests/projects.test.js
> +    expect(response.body.error).toBeFalsy();
I would add `"expect(response.body.data)"` for the endpoints that save this information.

2022-10-25 18:16 UTC, PilarFernandezC commented on src/tests/projects.test.js
> +    expect(response.body.error).toBeFalsy();
done

2022-10-26 20:35 UTC, matiasraviola submitted a review, later dismissed

2022-10-27 01:02 UTC, paurinaldi approved these changes

2022-10-27 01:07 UTC, matiasraviola submitted a review, later dismissed

2022-10-27 12:08 UTC, paurinaldi approved these changes

2022-10-27 12:08 UTC, merged