BaSP-TG-25: Super Admin Unit Test - create, getById and delete
BaSP-a2022/ayom-a-trackgenix-server pull request #45
Opened 2022-10-25 23:08 UTC by PilarFernandezC

- create: tests when you send a correct body, a wrong body, a wrong route or you don´t send anything
- delete: tests when you send a correct ID, a wrong ID, a wrong route or you don´t send anything
- getById: tests when you send a correct ID, a wrong ID or a wrong route

2022-10-26 21:01 UTC, matiasraviola requested changes

2022-10-26 21:01 UTC, matiasraviola commented on src/seeds/projects.js
>      _id: mongoose.Types.ObjectId('63544791fc13ae64f60000b5'),
_id: could be employeeId to have the same names as in the schema

2022-10-26 21:19 UTC, PilarFernandezC commented on src/seeds/projects.js
>      _id: mongoose.Types.ObjectId('63544791fc13ae64f60000b5'),
done

2022-10-27 00:43 UTC, matiasraviola approved these changes

2022-10-27 01:34 UTC, paurinaldi submitted a review, later dismissed

2022-10-27 12:09 UTC, paurinaldi approved these changes

2022-10-27 12:09 UTC, merged