BaSP-TG-24: Admin Unit Test - getAll & getById
BaSP-a2022/ayom-a-trackgenix-server pull request #46
Opened 2022-10-25 23:17 UTC by matiasraviola

[getAll]: tested when you try to get all the list, filter by each field and when the route is wrong
[getById]: tested when you try to get a valid and/or invalid ID.

2022-10-26 17:16 UTC, PilarFernandezC commented on src/tests/admins.test.js
> +    expect(response.status).toBe(200);
You could add a message test here (`response.body.message`). I think you could add it in other test cases too

2022-10-26 20:43 UTC, matiasraviola commented on src/tests/admins.test.js
> +    expect(response.status).toBe(200);
done

2022-10-26 21:25 UTC, PilarFernandezC approved these changes

2022-10-27 01:39 UTC, paurinaldi requested changes
Please check that getById function has the catch logic we talked about at the planning, as you correctly did with the other controller you are testing (getAllAdmins).

2022-10-27 01:52 UTC, matiasraviola commented
changes are already done

2022-10-27 02:16 UTC, paurinaldi approved these changes

2022-10-27 02:16 UTC, merged