BaSP-TG-32: Admin Unit Test - createAdmin, editAdmin & deleteAdmin
BaSP-a2022/ayom-a-trackgenix-server pull request #47
Opened 2022-10-25 23:17 UTC by mgriolfo-g

- createAdmin `[POST]` : checked 201 status, error false, not undefined data and correct message with proper admin (also minimum length name of 3)
- editAdmin `[PUT]` : checked 200 status with valid ID, error status for invalid ID, empty ID & empty body
- deleteAdmin `[DELETE]` : checked 204 status with valid ID, error status for empty ID, incorrect route. empty body & nonexistent ID (data undefined and error message)

2022-10-26 17:47 UTC, PilarFernandezC requested changes

2022-10-26 17:47 UTC, PilarFernandezC commented on src/tests/admins.test.js
> +    expect(response.status).toBe(500);
same here

2022-10-26 17:47 UTC, PilarFernandezC commented on src/tests/admins.test.js
> +    expect(response.status).toBe(500);
Status code 400 or 500?

2022-10-26 17:47 UTC, PilarFernandezC commented on src/controllers/admins.js
>        data: result,
The throw is missing here, you should add it between line 12 and line 13. Just like you did in the others.

2022-10-27 01:56 UTC, paurinaldi commented on src/tests/admins.test.js
> +    expect(response.status).toBe(500);
To add to pilar's comments, code 500 is ok, the test passes because the server fails since we are passing wrong route, but please check that you keep consistency in the description of the test 
  test('Should return status code 500.. etc

2022-10-27 04:31 UTC, mgriolfo-g commented on src/tests/admins.test.js
> +    expect(response.status).toBe(500);
Great then! I did not know which one to keep, so now I'll change both of the tests descriptions to 500! Thanks :D

2022-10-27 04:34 UTC, mgriolfo-g commented on src/controllers/admins.js
>        data: result,
I may be wrong, but aren't throw sentences only used on ERROR cases? I thought that a throw was not implied here, since 201 is a correct status code. May I ask for your knowledge for assistance on this conflict @paurinaldi ? Thanks in advance 🤗

2022-10-27 13:59 UTC, paurinaldi commented on src/controllers/admins.js
>        data: result,
as we talked about in the planning, it is good to throw an error in case our request hasn't passed because an error we made (like not filling all required fields, or something of the sort). In this case, you could make it with an if (!result), meaning that if the new admin isn't created, you could throw status code 400

2022-10-27 14:09 UTC, PilarFernandezC requested changes

2022-10-27 14:09 UTC, PilarFernandezC commented on src/controllers/admins.js
>        data: result,
Something like this
`const createAdmin = async (req, res) => {`
  `try {`
    `const admin = new Admins({`
      `name: req.body.name,`
      `lastName: req.body.lastName,`
      `email: req.body.email,`
      `password: req.body.password,`
    `});`
    `const result = await admin.save();`
    `if (!result){`
        `throw {`
            `message: 'Could not create admin', status: 400,`
        `};`
    `}`
    `return res.status(201).json({`
      `message: 'Admin created successfully',`
      `data: result,`
   `});`
  `} catch (error) {`
    `return res.status(error.status || 500).json({`
      `message: error.message || error,`
    `});`
  `}`
`};`

2022-10-27 16:32 UTC, mgriolfo-g commented on src/controllers/admins.js
>        data: result,
Ooooh, thought you were talking about the 201 code! Thanks for your observation, a throw for a 400 status was now added!

2022-10-27 17:38 UTC, PilarFernandezC approved these changes

2022-10-27 18:06 UTC, ignacioaristo approved these changes

2022-10-27 22:20 UTC, ignacioaristo approved these changes

2022-10-27 22:20 UTC, merged