BaSP-TG-33: Super Admin Unit Test - GetAll- Edit
BaSP-a2022/ayom-a-trackgenix-server pull request #48
Opened 2022-10-26 01:08 UTC by LucianoFranchino

GetAll created

2022-10-26 21:06 UTC, matiasraviola commented on src/tests/projects.test.js
> +      expect(response.body.message).toBe('Projects found');
You can also test if the "name" filter is going good too

2022-10-26 21:07 UTC, matiasraviola commented on src/tests/superAdmin.test.js
> +    expect(response.body.message).toBe('SuperAdmins found');
The same here, you can test "name"/""lastName"/"email" filters as well

2022-10-27 19:10 UTC, paurinaldi requested changes

2022-10-27 19:10 UTC, paurinaldi commented on src/controllers/superAdmin.js
> +    return res.status(error.status || 400 || 500).json({
this line is wrong, it should be res.status(error.status || 500), delete 400

2022-10-27 22:57 UTC, merged