BaSP-TG-27 Timesheet unit test
BaSP-a2022/ayom-a-trackgenix-server pull request #49
Opened 2022-10-26 02:15 UTC by eyrent

### Important
This is **WORK IN PROGRESS**. Unfortunatelly some of the PUT tests are not finished yet. I've discovered inconsistencies during testing that were NOT address yet. Please, bear that in mind.
### Tests added
- `[POST]` `/api/timesheets/` _(id as path param)_
    ✓ sending ALL required data fields (NOMINAL)
    ✓ sending only SOME data fields (NOT ALLOWED)
    ✓ with ALL fields and an UNEXPECTED ID path param (NOT ALLOWED)
    ✓ with ALL fields and an UNEXPECTED ID PROPERTY in request body (NOT ALLOWED)
    ✓ with ALL fields and UNEXPECTED and relevant query params (NO EFFECT)
    ✓ <hours> OUT OF RANGE (NOT ALLOWED)
    ✓ <date> is LATER THAN TODAY (NOT ALLOWED)
- `[PUT]` `/api/timesheets/` _(id as path param)_
   ✓ with a VALID EXISTENT ID and ALL VALID DATA FIELDS sent in the body (NOMINAL)
   ✓ with a VALID EXISTENT ID and SOME VALID DATA FIELDS sent in the body (NOMINAL)
   ✓ with a VALID EXISTENT ID and SOME INVALID DATA FIELDS sent in the body (NOT NOMINAL)
### Coming soon
- `[PUT]` `/api/timesheets/`
   🗘 with an VALID NON-EXISTENT ID and ALL DATA FIELDS sent in the body (FAILS) (48 ms)
   🗘 with an INVALID ID and ALL DATA FIELDS sent in the body (FAILS) (55 ms)
   🗘 WITHOUT an ID and ALL DATA FIELDS sent in the body (46 ms)

2022-10-27 02:09 UTC, paurinaldi requested changes
please check that createTimesheet controller has throw logic as the others do

2022-10-27 06:46 UTC, eyrent commented on src/tests/timesheets.test.js
> +  });
Do you mean the whole path? Or the id in the path?

2022-10-27 13:05 UTC, paurinaldi requested changes

2022-10-27 13:05 UTC, paurinaldi commented on src/controllers/timeSheet.js
> +    if (error instanceof Joi.ValidationError) error.status = 400;
this line is unnecesarry and not according to what we talked in the planning, please check how we made it on other controllers and change it on all functions to keep consistency

2022-10-27 13:11 UTC, Martinzancocchia commented on src/tests/timesheets.test.js
> +  });
the whole path

2022-10-27 17:57 UTC, eyrent commented on src/controllers/timeSheet.js
> +    if (error instanceof Joi.ValidationError) error.status = 400;
I understand. I did this to have Joi messages from validation errors reported in the response with a 400 status (since I think that's preferred over the 500 that was given before). Otherwise that message is lost, I guess. Anyhow I'm complying to your comment cause probably that would generate inconsistencies. What do you think?

2022-10-27 17:58 UTC, eyrent commented on src/controllers/timeSheet.js
> +    throw {
I mean the condition is inside Joi's code. It's been thrown from within the validation and with that type of error. I can also look for another condition to sort the status issue.

2022-10-27 17:59 UTC, eyrent commented on src/controllers/timeSheet.js
> +    if (error instanceof Joi.ValidationError) error.status = 400;
I mean the condition is inside Joi's code. It's been thrown from within the validation and with that type of error. I can also look for another condition to sort the status issue.

2022-10-27 18:51 UTC, eyrent commented on src/tests/timesheets.test.js
> +  });
For example when trying to hit `api/NotAValidPath`?

2022-10-27 18:52 UTC, eyrent commented on src/controllers/timeSheet.js
> +    throw {
Yes. Indeed I mised the else block in that if-else. I'm changing it right away.

2022-10-27 18:54 UTC, eyrent commented
Would you accept the response format I gave above? Are there problems with that?

2022-10-27 19:18 UTC, eyrent commented on src/controllers/timeSheet.js
> +    throw {
However I tried changing it to this: 
```
if (result) {
      return res.status(201).json({
        message: 'Timesheet created successfully.',
        data: result,
        error: false,
      });
    } else {
    // eslint-disable-next-line no-throw-literal
      throw {
        message: 'Timesheet creation failed.',
        status: 500,
      };
    }
```
And got this form the linter:
```
/home/fabricio/Documents/RR-BaSP/Trackgenix-backend/ayom-a-trackgenix-server/src/controllers/timeSheet.js
  34:12  error  Unnecessary 'else' after 'return'  no-else-return
```

2022-10-27 19:23 UTC, eyrent commented on src/controllers/timeSheet.js
> +    throw {
Done!

2022-10-28 03:09 UTC, ignacioaristo approved these changes

2022-10-28 03:09 UTC, merged