BASP-TG-51: Timesheet fix filterByDescription
BaSP-a2022/ayom-a-trackgenix-server pull request #56
Opened 2022-11-04 21:13 UTC by CristianBucci

Fix filterByDescription endpoint to get the request timesheet filtered by description!

2022-11-04 21:58 UTC, matescarabino requested changes
This fixes it, I already tested it in postman

2022-11-04 21:58 UTC, matescarabino commented on src/controllers/timeSheet.js
> +    return res.status(200).json({
It still returns an empty array if a nonexistent attribute is entered in the filters. This fixes it (after line 103 and before the "catch")
 
```suggestion
        if (filterByParams.length !== 0) {
      return res.status(200).json({
        message: 'Timesheet found',
        data: filterByParams,
        error: false,
      });
    }
    return res.status(404).json({
      message: 'Timesheet not found',
      error: true,
    });
```

2022-11-05 03:50 UTC, CristianBucci commented on src/controllers/timeSheet.js
> +    return res.status(200).json({
Fixed! I find other way to do it without change the tests

2022-11-06 22:21 UTC, matescarabino approved these changes

2022-11-06 22:27 UTC, ignacioaristo approved these changes

2022-11-07 13:41 UTC, NicoSan02 approved these changes

2022-11-07 13:43 UTC, merged