BaSP-TG: Created /super-admin endpoint. Added editing and filtering functionality.
BaSP-a2022/ayom-a-trackgenix-server pull request #6
Opened 2022-10-10 18:32 UTC by eyrent

New routing in `index.js`: 
```
/super-admin/<endpoint>
```
New endpoints, in `super-admins.js`:

2022-10-12 00:06 UTC, eyrent commented
Me acaban de avisar que en la linea 27 hay un typo. Debería decir `password` en lugar de `pasword`. Lo corrijo junto con los demás comentarios

2022-10-12 14:35 UTC, ignacioaristo requested changes

2022-10-12 14:35 UTC, ignacioaristo commented on src/index.js
> +const superadmin = require('./resources/super-admins');
Use camelCase here.

2022-10-12 18:45 UTC, eyrent commented on src/resources/super-admins.js
> +router.put('/editById', (req, res) => {
To confirm (or revoke): `id` is sent via URI params (path) and the properties to be edited are sent in the body of the request. Alternatively, all properties can be sent in the path (but that would expose sensitive data). I'd rather go with the first option, but you've got the last word.

2022-10-12 19:46 UTC, ignacioaristo commented on src/resources/super-admins.js
> +router.put('/editById', (req, res) => {
You have a point, lets keep it in this way.

2022-10-12 22:56 UTC, eyrent commented on src/resources/super-admins.js
> +  } = req.query;
I'll sum up how I approached this fix: I'll be using a path param called `filters` which is a comma (`','`) separated list of possible filters to apply to the search. If the client would need to not filter by some parameter, a `'*'` is given instead of an empty place. This is in case it might be desirable to search for empty fields (for some reason). Therefore,

2022-10-13 01:40 UTC, eyrent commented on src/index.js
> +const superadmin = require('./resources/super-admins');
Done! I kept the filenames.

2022-10-13 01:40 UTC, eyrent commented on src/resources/super-admins.js
> +router.put('/editById', (req, res) => {
Done!

2022-10-13 12:55 UTC, ignacioaristo approved these changes
Good job!

2022-10-13 12:55 UTC, merged