BaSP-TG: Project endpoints added
BaSP-a2022/ayom-a-trackgenix-server pull request #8
Opened 2022-10-10 22:43 UTC by LucianoFranchino

Endpoints:
- Create Project
- Get all
- Get by Id

2022-10-12 14:57 UTC, ignacioaristo requested changes

2022-10-12 14:57 UTC, ignacioaristo commented on src/index.js
> +const port = process.env.PORT || 6000;
let keep the port in 3000.

2022-10-12 14:57 UTC, ignacioaristo commented on src/index.js
> +const callRouter = require('./resources/projects');
we could be more specific with this name, for e.g: projectsRouter

2022-10-12 14:57 UTC, ignacioaristo commented on src/index.js
> +app.use(express.urlencoded({ extended: false }));
Is this line necessary for now?

2022-10-12 23:55 UTC, LucianoFranchino commented on src/index.js
> +const port = process.env.PORT || 6000;
Resolved!

2022-10-12 23:55 UTC, LucianoFranchino commented on src/index.js
> +const callRouter = require('./resources/projects');
Resolved!

2022-10-12 23:56 UTC, LucianoFranchino commented on src/index.js
> +app.use(express.urlencoded({ extended: false }));
I think that line was already in the file, I deleted it anyway!

2022-10-13 20:40 UTC, ignacioaristo approved these changes
Good job

2022-10-13 20:40 UTC, merged