BaSP-TG: getTaskByDesc and addNewTask endpoints added
BaSP-a2022/ayom-a-trackgenix-server pull request #9
Opened 2022-10-11 01:24 UTC by Martinzancocchia

2022-10-12 18:14 UTC, paurinaldi requested changes
Adding to other comments left, I need you to check that the server can run before pushing. There are some slint errors, and the missing [ ] on admins json. Also, tasks json data needs to be on this branch as well as neccesary logic on index, so we can run the methods.

2022-10-12 18:21 UTC, paurinaldi requested changes

2022-10-12 18:21 UTC, paurinaldi commented on src/resources/tasks.js
> +    fileSystem.writeFile('src/data/tasks.json', JSON.stringify(tasks, null, 4), (err) => {
null and 4 are unnecesary params, please delete

2022-10-13 02:06 UTC, paurinaldi requested changes
Martin, I still can't run the server, check previous comment I left.

2022-10-13 18:12 UTC, Martinzancocchia commented on src/resources/tasks.js
> +router.post('/addNewTask', (req, res) => {
done!

2022-10-13 18:12 UTC, Martinzancocchia commented on src/resources/tasks.js
> +  router.get('/getTaskByDesc', (req, res) => {
fixed!

2022-10-13 18:12 UTC, Martinzancocchia commented on src/resources/tasks.js
> +    fileSystem.writeFile('src/data/tasks.json', JSON.stringify(tasks, null, 4), (err) => {
done!

2022-10-13 18:21 UTC, ignacioaristo approved these changes

2022-10-13 18:22 UTC, merged